In [3]:
import tensorflow as tf

2021-11-13 17:10:59.441353: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-11-13 17:10:59.441387: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/digipodium/Datasets/main/credit-card.csv')

In [6]:
df

,Unnamed: 0,Time,V1,V2,V3,V4,V5,V6,V7,V8,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,541,406.0,-2.312227,1.951992,-1.609851,3.997906,-0.522188,-1.426545,-2.537387,1.391657,...,0.517232,-0.035049,-0.465211,0.320198,0.044519,0.177840,0.261145,-0.143276,0.00,1
1,623,472.0,-3.043541,-3.157307,1.088463,2.288644,1.359805,-1.064823,0.325574,-0.067794,...,0.661696,0.435477,1.375966,-0.293803,0.279798,-0.145362,-0.252773,0.035764,529.00,1
2,4920,4462.0,-2.303350,1.759247,-0.359745,2.330243,-0.821628,-0.075788,0.562320,-0.399147,...,-0.294166,-0.932391,0.172726,-0.087330,-0.156114,-0.542628,0.039566,-0.153029,239.93,1
3,6108,6986.0,-4.397974,1.358367,-2.592844,2.679787,-1.128131,-1.706536,-3.496197,-0.248778,...,0.573574,0.176968,-0.436207,-0.053502,0.252405,-0.657488,-0.827136,0.849573,59.00,1
4,6329,7519.0,1.234235,3.019740,-4.304597,4.732795,3.624201,-1.357746,1.713445,-0.496358,...,-0.379068,-0.704181,-0.656805,-1.632653,1.488901,0.566797,-0.010016,0.146793,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9487,207634,136765.0,-5.493186,4.057918,-1.795148,-0.522112,-3.901231,-0.338767,-4.216907,1.655481,...,2.827709,-0.480805,0.883135,0.476372,-0.422392,0.266097,-1.249686,-0.237272,0.74,0
9488,210369,137949.0,1.939843,-0.434933,-0.345178,0.307799,-0.487803,0.113880,-0.729222,0.152521,...,0.246981,0.914658,0.141960,0.799542,-0.099047,-0.270436,0.035708,-0.038128,9.99,0
9489,211880,138612.0,1.798427,-0.160432,-1.920048,1.051255,1.204895,0.892956,0.324847,0.194731,...,0.176878,0.684760,-0.019825,-1.506229,0.238479,-0.389693,0.019441,-0.080415,55.00,0
9490,273066,165405.0,2.114637,-0.211168,-1.638108,-0.010894,0.490466,-0.130107,-0.015770,-0.042934,...,-0.339011,-0.921378,0.170633,-1.413620,-0.180180,0.266670,-0.082983,-0.086125,1.98,0
9491,126327,77984.0,-0.298551,1.100801,0.841074,-0.335169,0.714700,0.023175,0.624201,0.112563,...,-0.282316,-0.739245,-0.182471,-0.871434,-0.013802,0.124734,0.244955,0.077531,1.98,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9492 entries, 0 to 9491
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  9492 non-null   int64
 1   Time        9492 non-null   float64
 2   V1          9492 non-null   float64
 3   V2          9492 non-null   float64
 4   V3          9492 non-null   float64
 5   V4          9492 non-null   float64
 6   V5          9492 non-null   float64
 7   V6          9492 non-null   float64
 8   V7          9492 non-null   float64
 9   V8          9492 non-null   float64
 10  V9          9492 non-null   float64
 11  V10         9492 non-null   float64
 12  V11         9492 non-null   float64
 13  V12         9492 non-null   float64
 14  V13         9492 non-null   float64
 15  V14         9492 non-null   float64
 16  V15         9492 non-null   float64
 17  V16         9492 non-null   float64
 18  V17         9492 non-null   float64
 19  V18         9492 non-null   float64
 20  V19         9492 non-null   float64
 21  V20         9492 non-null   float64
 22  V21         9492 non-null   float64
 23  V22         9492 non-null   float64
 24  V23         9492 non-null   float64
 25  V24         9492 non-null   float64
 26  V25         9492 non-null   float64
 27  V26         9492 non-null   float64
 28  V27         9492 non-null   float64
 29  V28         9492 non-null   float64
 30  Amount      9492 non-null   float64
 31  Class       9492 non-null   int64
dtypes: float64(30), int64(2)
memory usage: 2.3 MB

In [8]:
x= df.iloc[:,:-1]

In [9]:
y= df['Class']

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
from sklearn.metrics import classification_report, confusion_matrix

In [13]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = .2)

In [14]:
x_shape = x.shape[1]

In [15]:
x_shape

31

## neural network architecture

In [16]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(
    units= 10,
    activation= 'relu',
    input_shape= (x_shape,)
))

2021-11-13 17:11:54.266105: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-11-13 17:11:54.266135: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-13 17:11:54.266160: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (linux): /proc/driver/nvidia/version does not exist
2021-11-13 17:11:54.266331: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [17]:
model.add(tf.keras.layers.Dense(
    units= 10,
    activation= 'relu',
))

In [20]:
model.add(tf.keras.layers.Dense(
    units= 1,
    activation= 'sigmoid',
))

In [22]:
# model.compile('sgd',loss= 'binary_crossentropy', metrics= ['accuracy']) 


model.compile('sgd', loss= 'binary_crossentropy', metrics= ['accuracy'])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 10)                320
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11
=================================================================
Total params: 441
Trainable params: 441
Non-trainable params: 0
_________________________________________________________________